Repository veryear/2048, pull requests merged in 2018-09, with the labels that each got.

#23 [UI/UX] 4x4 게임판 만들기
  app.py
  drawBlock.py
Labels: UI/UX, development

#24 [UI/UX] 게임판에 블럭 만들기
  .gitignore
  block.py
  drawBlock.py
Labels: UI/UX, development

#25 블럭 움직이는 함수 구현
  block.py
  constants.py
  drawBlock.py
Labels: UI/UX, development

#26 Feature/define arrow keys
  app.py
  constants.py
  drawBlock.py
  keyboardInput.py
Labels: UI/UX, development

#30 #29 [UI/UX] moveBlock함수 파라미터 매개변수 추가
  drawBlock.py
Labels: UI/UX, development

#31 refresh(update) screen after move block
  drawBlock.py
Labels: UI/UX, development

#32 Feature/make game scord and timer
  app.py
  constants.py
  drawBlock.py
  game.py
  gameInfo.py
Labels: UI/UX

#34 Feature/calc blockvalue
  block.py
  drawBlock.py
  game.py
  randomValue.py
Labels: algorithm, development
